#!/bin/bash

# Backup all old dotfiles
mkdir ~/.config_old
mv ~/.config  ~/.config_old
mv ~/.Xresources ~/.xinitrc ~/.bashrc ~/.bash_profile ~/.config_old

# Actually install the dotfiles
stow X
stow bash
stow bspwm
stow picom 

