#! /bin/sh
# cleanbaja's bspwm config :-)

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom -c --config ~/.config/picom/picom.conf &
$HOME/polybar-collection/launch.sh &
feh --bg-scale --randomize ~/Wallpapers/*

# Workspaces
bspc monitor -d 1 2 3 4 5

# Random Options
bspc config border_width         0
bspc config window_gap           18
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs    state=tiled

# Multiple Monitors
# TODO: Use multiple monitors by checking for script & xrandr

